#!/bin/bash

#inputType="-s"
#input="<a href='bla_bla_bla'>hi</p>"

rm -f report.xml

testData="./html5libTests/data/tests*"

inputType="-f"
#input="/home/mbgppja7/Documents/HTML5Parser/html5libTests/data/adoption01/1.txt"

#for filename in $(ls -R $testData/ *.txt); do
equals=0
different=0
echo "Report" > results.txt
for filename in $(find $testData -name '*.txt'); do
	echo 'Processing '$filename
	parse5output=`node parse5/parser5.js "$inputType" "$filename"`
	jsoupOutput=`java -jar jsoup/JsoupParser.jar "$inputType" "$filename"`
	html5libOutput=`python html5lib/html5libRunner.py "$inputType" "$filename"`
	
	echo `java -jar Comparator.jar "$filename" "$parse5output" "parse5" "$jsoupOutput" "jsoup" "$html5libOutput" "html5lib"`

done

